import type { CampusEvent } from "./types";

export const mockEvents: CampusEvent[] = [
  {
    id: "evt-hackathon",
    title: "Fall Build Night",
    description:
      "A four-hour build sprint for whatever you've been meaning to ship. Mentors from the CS department drop by after 7.",
    category: "workshop",
    format: "in-person",
    startsAt: "2026-10-03T17:00:00",
    endsAt: "2026-10-03T21:00:00",
    venue: "Innovation Lab, Rieger 2nd Floor",
    capacity: 60,
    seedRegisteredCount: 41,
    registrationOpen: true,
  },
  {
    id: "evt-resume",
    title: "Resumes That Get Read",
    description:
      "A career-center workshop on cutting your resume down to what recruiters actually look at. Bring a draft.",
    category: "career",
    format: "online",
    startsAt: "2026-10-06T12:00:00",
    endsAt: "2026-10-06T13:00:00",
    joinUrl: "https://connectsphere.zoom.us/j/resumes-workshop",
    capacity: 30,
    seedRegisteredCount: 30,
    seedWaitlistCount: 4,
    registrationOpen: true,
  },
  {
    id: "evt-fallfest",
    title: "Fall Fest Block Party",
    description:
      "Food trucks, a student-band lineup, and the annual pumpkin catapult on the East Quad lawn.",
    category: "social",
    format: "in-person",
    startsAt: "2026-10-09T18:00:00",
    endsAt: "2026-10-09T22:00:00",
    venue: "East Quad Lawn",
    capacity: 400,
    seedRegisteredCount: 128,
    registrationOpen: true,
  },
  {
    id: "evt-jazz",
    title: "Late Jazz: Student Combo Night",
    description:
      "The jazz combo class closes out the semester with a short set in the recital hall. Doors at 7:30.",
    category: "performance",
    format: "in-person",
    startsAt: "2026-10-15T20:00:00",
    endsAt: "2026-10-15T21:30:00",
    venue: "Ellsworth Recital Hall",
    capacity: 90,
    seedRegisteredCount: 90,
    seedWaitlistCount: 2,
    registrationOpen: true,
  },
  {
    id: "evt-figma",
    title: "Intro to Prototyping in Figma",
    description:
      "Hands-on session for building a clickable prototype from scratch. Laptops provided if you don't have one.",
    category: "workshop",
    format: "in-person",
    startsAt: "2026-10-19T16:30:00",
    endsAt: "2026-10-19T18:30:00",
    venue: "Design Studio, Art Building 3",
    capacity: 24,
    seedRegisteredCount: 9,
    registrationOpen: true,
  },
];
